// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_OAtbvVnqhX4e6dYFdEscS0w5lVPpq3I',
    appId: '1:557982579011:web:7ad76e64d1ba49f65cd7f6',
    messagingSenderId: '557982579011',
    projectId: 'cepattanggap-1b143',
    authDomain: 'cepattanggap-1b143.firebaseapp.com',
    storageBucket: 'cepattanggap-1b143.firebasestorage.app',
    measurementId: 'G-RMT1R0V01L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-6ELErVu--hBJe1UM8IRbt01Umv5HFEY',
    appId: '1:557982579011:android:4295399800389ac65cd7f6',
    messagingSenderId: '557982579011',
    projectId: 'cepattanggap-1b143',
    storageBucket: 'cepattanggap-1b143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACY26srCpoBIUBL85wGa6ddwzaoKQdj7I',
    appId: '1:557982579011:ios:fc51f665bf7145335cd7f6',
    messagingSenderId: '557982579011',
    projectId: 'cepattanggap-1b143',
    storageBucket: 'cepattanggap-1b143.firebasestorage.app',
    iosBundleId: 'com.example.cepattanggap',
  );
}
